version: "3.8"

services:
  app:
    build: .
    container_name: savanna-isp-app
    environment:
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_NAME: savanna_db
      DB_USERNAME: savanna_user
      DB_PASSWORD: Eduardo1234
      DB_SSL_MODE: disable
      SERVER_PORT: 8086
      SPRING_PROFILES_ACTIVE: default
      CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:4200,https://savanna-green.cloud,https://www.savanna-green.cloud"
    network_mode: "host"
